name: First job
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ls all folders
        run: ls -alh 
      
